Remaining: 4794 Maximum: 5000

Total comments to retrieve:  66389
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
     Process is sleeping 1 hour due maximum rate limit reached.

(5000, 5000)
Remaining: 3803Maximum: 5000

Write repository's name (format: creator/repository): Traceback (most recent call last):
  File "github-script.py", line 7, in <module>
    github_repo = input("Write repository's name (format: creator/repository): ")
OSError: [Errno 9] Bad file descriptor
Remaining: 4830 Maximum: 5000

Total issues and pull requests to retrieve:  20568
     0%
(4910, 5000)
------------------------------ 
 Getting issues events from mono/mono 
 ------------------------------
Total events to retrieve:  40000
(4968, 5000)
Total comments to retrieve:  40000
     0%
     10.0 %,    remaining: 4926
     20.0 %,    remaining: 4886
     30.0 %,    remaining: 4846
     40.0 %,    remaining: 4806
     50.0 %,    remaining: 4766
     60.0 %,    remaining: 4726
     70.0 %,    remaining: 4686
     80.0 %,    remaining: 4646
     90.0 %,    remaining: 4606
     100.0 %,    remaining: 4566
(4566, 5000)
Total comments to retrieve:  18900
     Process finished by unspected reason: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 685, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 752, in read_chunked
    self._update_chunk_length()
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 689, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 560, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 781, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aaron_smartinez1997/GitHubAnalyzer/github_handler.py", line 291, in get_pulls_comments
    comment = pulls_comments[c]
  File "/home/aaron_smartinez1997/.local/lib/python3.8/site-packages/github/PaginatedList.py", line 50, in __getitem__
    self.__fetchToIndex(index)
  File "/home/aaron_smartinez1997/.local/lib/python3.8/site-packages/github/PaginatedList.py", line 68, in __fetchToIndex
    self._grow()
  File "/home/aaron_smartinez1997/.local/lib/python3.8/site-packages/github/PaginatedList.py", line 71, in _grow
    newElements = self._fetchNextPage()
  File "/home/aaron_smartinez1997/.local/lib/python3.8/site-packages/github/PaginatedList.py", line 203, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/aaron_smartinez1997/.local/lib/python3.8/site-packages/github/Requester.py", line 318, in requestJsonAndCheck
    *self.requestJson(
  File "/home/aaron_smartinez1997/.local/lib/python3.8/site-packages/github/Requester.py", line 410, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/aaron_smartinez1997/.local/lib/python3.8/site-packages/github/Requester.py", line 486, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/aaron_smartinez1997/.local/lib/python3.8/site-packages/github/Requester.py", line 513, in __requestRaw
    response = cnx.getresponse()
  File "/home/aaron_smartinez1997/.local/lib/python3.8/site-packages/github/Requester.py", line 110, in getresponse
    r = verb(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 686, in send
    r.content
  File "/usr/lib/python3/dist-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/lib/python3/dist-packages/requests/models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
 

Remaining: 4988Maximum: 5000

Total comments to retrieve:  122253
     Process is sleeping 1 hour due maximum rate limit reached.

     Process finished by unspected reason: Traceback (most recent call last):
  File "/home/aaron_smartinez1997/GitHubAnalyzer/github_handler.py", line 597, in get_commits_pulls
    g = check_rate_limit(g)
  File "/home/aaron_smartinez1997/GitHubAnalyzer/github_handler.py", line 18, in check_rate_limit
    g = Github(github_token)
NameError: name 'github_token' is not defined
 

Remaining: 20Maximum: 5000

Total issues and pull requests to retrieve:  20568
     Process is sleeping 1 hour due maximum rate limit reached.

Traceback (most recent call last):
  File "/home/aaron_smartinez1997/GitHubAnalyzer/github_handler.py", line 522, in get_pulls_commits
    g = check_rate_limit(g)
  File "/home/aaron_smartinez1997/GitHubAnalyzer/github_handler.py", line 18, in check_rate_limit
    g = Github(github_token)
NameError: name 'github_token' is not defined

(19, 5000)
Traceback (most recent call last):
  File "github-script.py", line 18, in <module>
    link_commits_pulls_and_issues(github_repo)
  File "/home/aaron_smartinez1997/GitHubAnalyzer/data_handler.py", line 214, in link_commits_pulls_and_issues
    linked_pull_issues = generate_json_from_csv("pull_no", workspace + "pull_request_analysis.csv")
  File "/home/aaron_smartinez1997/GitHubAnalyzer/data_handler.py", line 46, in generate_json_from_csv
    with open(csv_path, "r") as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'mono/files/pull_request_analysis.csv'
